baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
[[module.imports]]
path = "github.com/willfaught/paige"

[[module.mounts]]
    source = 'content'
    target = 'content'
    
[[module.mounts]]
    source = 'test_content'
    target = 'content'